float64 t                          # Time 
#float64[12] qJ                     # Joint position commands
#float64[12] vJ                     # Joint velocity commands
#float64[12] tauJ                   # Joint torque commands

float64[12] qj                     # Joint position commands
float64[12] vj                     # Joint velocity commands
float64[12] tauj                   # Joint torque commands
#float64[12] Kp                     # Joint position gain commands
#float64[12] Kd                     # Joint velocity gain commands
float64[12] kp                     # Joint position gain commands
float64[12] kd                     # Joint velocity gain commands